# MAKE SURE TO RENAME THIS FILE TO config.toml AND PLACE IT IN THE ROOT OF THE PROJECT

node_name = "example_node"

# Router configuration
router_name = "router1"
router_address = "xx.xx.xx.xx"  # Replace with actual IP address
router_port = 5555

# Rotary encoder serial adress
rotary_encoder_address = "/dev/tty.usbmodem1101"

# Timetagger configuration (provider_name, instrument_name)
timetagger = ["provider", "tagger"] # Replace with actual provider and instrument names

# Bell state configuration (default: Phi_plus)
bell_state = 0

# CHSH experiment settings
[chsh_settings]
hwp = ["provider", "instrument_hwp"]  # Replace with actual HWP names
request_hwp = ["provider", "instrument_hwp"]

# CHSH measurement configuration
[chsh_settings.measurement_config]
integration_time_s= 5
binwidth = 500
channel1 = 1
channel2 = 2
dark_count = 0

# QKD experiment settings
[qkd_settings]
hwp = ["provider", "instrument_hwp"]
request_hwp = ["provider", "instrument_hwp"]
bitstring_length = 4
discriminating_threshold = 10

# QKD measurement configuration
[qkd_settings.measurement_config]
integration_time_s = 5
binwidth = 500
channel1 = 1
channel2 = 2
dark_count = 0