#!/usr/bin/env python
from ThorlabsPM100 import ThorlabsPM100, USBTMC
import time
import logging
from datetime import datetimei

inst1 = USBTMC(device="/dev/usbtmc0")
inst2 = USBTMC(device="/dev/usbtmc1")
pm1 = ThorlabsPM100(inst=inst1)
pm2 = ThorlabsPM100(inst=inst2)
logging.basicConfig(
    filename='/.txt',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

while True:
    p1 = pm1.read
    p2 = pm2.read
    now = datetime.now()
    timestamp = now.timestamp()
    msg = f"Powermeter 1: {p1:.6e}, Powermeter 2: {p2:.6e}. Timestamp: {timestamp}"
    logging.info(msg)
    time.sleep(0.001)
