#!/usr/bin/env python
from ThorlabsPM100 import ThorlabsPM100, USBTMC
import time

inst = USBTMC(device="/dev/usbtmc0")
pm = ThorlabsPM100(inst=inst)

while True:
    p = pm.read
    print(f"\rPower: {p:.6e} W", end="", flush=True)
    time.sleep(0.1)

