#!/usr/bin/env python
import datetime
import time
from dataclasses import dataclass

from pqnstack.constants import DEFAULT_SETTINGS
from pqnstack.constants import MeasurementBasis
from pqnstack.pqn.drivers.powermeter import PM100D
from pqnstack.pqn.drivers.rotator import ELL14KRotator
from pqnstack.base.datalogger import DataLogger

_TOMOGRAPHY_STATES: list[str] = ["H", "V", "D", "A", "R", "L"]

TOMOGRAPHY_BASIS: MeasurementBasis = MeasurementBasis(
    name="TOMOGRAPHY",
    pairs=[(s, i) for s in _TOMOGRAPHY_STATES for i in _TOMOGRAPHY_STATES],
    settings=DEFAULT_SETTINGS,
)

signal_qwp = ELL14KRotator(name = "signal_qwp", desc = "first_qwp", hw_address = "/dev/usbtmc1", offset_degrees = 22.5)
signal_hwp = ELL14KRotator(name = "signal_hwp", desc = "first_hwp", hw_address = "/dev/usbtmc1", offset_degrees = 88.49)
idler_qwp = ELL14KRotator(name = "idler_qwp", desc = "second_qwp", hw_address = "/dev/usbtmc1", offset_degrees = 201.498)
idler_hwp = ELL14KRotator(name = "idler_hwp", desc = "second_hwp", hw_address = "/dev/usbtmc1", offset_degrees = 46.41)
anciliary_qwp = ELL14KRotator(name = "useless_qwp", desc = "third_qwp", hw_address = "/dev/usbtmc1", offset_degrees = 129.5)

h_powermeter = PM100D(name = "h_power", desc = "h_power_meter", hw_address = "/dev/usbtmc1")
v_powermeter = PM100D(name = "v_power", desc = "v_power_meter", hw_address = "/dev/usbtmc1")

data_logger = DataLogger()
data_logger.add_instrument(h_powermeter)
data_logger.add_instrument(v_powermeter)

for signal_state, idler_state in TOMOGRAPHY_BASIS.pairs:
    signal_angles: tuple[float, float] = TOMOGRAPHY_BASIS.settings[signal_state]
    idler_angles: tuple[float, float] = TOMOGRAPHY_BASIS.settings[idler_state]

    signal_hwp.degrees=signal_angles[0]
    signal_qwp.degrees=signal_angles[1]
    idler_hwp.degrees=idler_angles[0]
    idler_qwp.degrees=idler_angles[1]
     
    data_logger.start_logging()
    time.sleep(3)
    data_logger.stop_logging()
