#!/usr/bin/env python

import logging

from pqnstack.network.node import Node

logging.basicConfig(level=logging.INFO)

if __name__ == "__main__":
    instruments = {
        "signal_hwp": {
            "import": "pqnstack.pqn.drivers.rotator.APTRotatorDevice",
            "desc": "signal hwp",
            "address": "83860312",
            "offset_degrees": 337.295,
        }
    }
    node = Node("ufl_closet", "172.30.63.109", 5555, **instruments)
    node.start()

