# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Checking Pull Request

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: pdm install
    - name: Lint with Ruff
      run: pdm run ruff check
    - name: Type check with Mypy
      run: pdm run mypy src/
    - name: Test with pytest
      run: pdm run pytest tests/pytest
